export const DOCKER_IMAGE_NAME = 'DOCKER_IMAGE_NAME';
export const DOCKER_IMAGE_TIMESTAMP = 'DOCKER_IMAGE_TIMESTAMP';
export const DOCKER_IMAGE_PREFIXES = 'DOCKER_IMAGE_PREFIXES';
export const DOCKER_IMAGE_ARCH = 'DOCKER_IMAGE_ARCH';
