/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedShowsRouteImport } from './routes/_protected/shows'
import { Route as ProtectedMoviesRouteImport } from './routes/_protected/movies'
import { Route as ProtectedLobbyRouteImport } from './routes/_protected/lobby'
import { Route as ProtectedListRouteImport } from './routes/_protected/list'
import { Route as ProtectedShowMediaIdRouteImport } from './routes/_protected/show.$mediaId'
import { Route as ProtectedSettingsSettingsRouteImport } from './routes/_protected/settings/_settings'
import { Route as ProtectedRoomsRoomIdRouteImport } from './routes/_protected/rooms.$roomId'
import { Route as ProtectedPlaylistPlaylistRouteImport } from './routes/_protected/playlist/_playlist'
import { Route as ProtectedPersonPersonIdRouteImport } from './routes/_protected/person.$personId'
import { Route as ProtectedMovieMediaIdRouteImport } from './routes/_protected/movie.$mediaId'
import { Route as ProtectedCompanyCompanyIdRouteImport } from './routes/_protected/company.$companyId'
import { Route as ProtectedCollectionCollectionIdRouteImport } from './routes/_protected/collection.$collectionId'
import { Route as ProtectedSettingsSettingsIndexRouteImport } from './routes/_protected/settings/_settings/index'
import { Route as ProtectedPlaylistPlaylistIndexRouteImport } from './routes/_protected/playlist/_playlist/index'
import { Route as ProtectedSettingsSettingsTermsRouteImport } from './routes/_protected/settings/_settings/terms'
import { Route as ProtectedSettingsSettingsProfileRouteImport } from './routes/_protected/settings/_settings/profile'
import { Route as ProtectedSettingsSettingsPrivacyRouteImport } from './routes/_protected/settings/_settings/privacy'
import { Route as ProtectedSettingsSettingsNotificationsRouteImport } from './routes/_protected/settings/_settings/notifications'
import { Route as ProtectedSettingsSettingsFaqRouteImport } from './routes/_protected/settings/_settings/faq'
import { Route as ProtectedSettingsSettingsDownloadsRouteImport } from './routes/_protected/settings/_settings/downloads'
import { Route as ProtectedSettingsSettingsActivityRouteImport } from './routes/_protected/settings/_settings/activity'
import { Route as ProtectedSettingsSettingsAdminRouteImport } from './routes/_protected/settings/_settings/_admin'
import { Route as ProtectedPlaylistPlaylistCreateRouteImport } from './routes/_protected/playlist/_playlist/create'
import { Route as ProtectedPlaylistPlaylistPlaylistIdRouteImport } from './routes/_protected/playlist/_playlist/$playlistId'
import { Route as ProtectedSettingsSettingsAdminPicksRouteImport } from './routes/_protected/settings/_settings/_admin/picks'
import { Route as ProtectedSettingsSettingsAdminPermissionsRouteImport } from './routes/_protected/settings/_settings/_admin/permissions'
import { Route as ProtectedSettingsSettingsAdminFramesRouteImport } from './routes/_protected/settings/_settings/_admin/frames'
import { Route as ProtectedSettingsSettingsAdminAccessRouteImport } from './routes/_protected/settings/_settings/_admin/access'
import { Route as ProtectedSettingsSettingsAdminLibrariesRouteImport } from './routes/_protected/settings/_settings/_admin/_libraries'
import { Route as ProtectedSettingsSettingsAdminLibrariesUnscannedRouteImport } from './routes/_protected/settings/_settings/_admin/_libraries/unscanned'
import { Route as ProtectedSettingsSettingsAdminLibrariesLibrariesRouteImport } from './routes/_protected/settings/_settings/_admin/_libraries/libraries'

const ProtectedSettingsRouteImport = createFileRoute('/_protected/settings')()
const ProtectedPlaylistRouteImport = createFileRoute('/_protected/playlist')()

const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPlaylistRoute = ProtectedPlaylistRouteImport.update({
  id: '/playlist',
  path: '/playlist',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedShowsRoute = ProtectedShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMoviesRoute = ProtectedMoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedLobbyRoute = ProtectedLobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedListRoute = ProtectedListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedShowMediaIdRoute = ProtectedShowMediaIdRouteImport.update({
  id: '/show/$mediaId',
  path: '/show/$mediaId',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsSettingsRoute =
  ProtectedSettingsSettingsRouteImport.update({
    id: '/_settings',
    getParentRoute: () => ProtectedSettingsRoute,
  } as any)
const ProtectedRoomsRoomIdRoute = ProtectedRoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPlaylistPlaylistRoute =
  ProtectedPlaylistPlaylistRouteImport.update({
    id: '/_playlist',
    getParentRoute: () => ProtectedPlaylistRoute,
  } as any)
const ProtectedPersonPersonIdRoute = ProtectedPersonPersonIdRouteImport.update({
  id: '/person/$personId',
  path: '/person/$personId',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMovieMediaIdRoute = ProtectedMovieMediaIdRouteImport.update({
  id: '/movie/$mediaId',
  path: '/movie/$mediaId',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCompanyCompanyIdRoute =
  ProtectedCompanyCompanyIdRouteImport.update({
    id: '/company/$companyId',
    path: '/company/$companyId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedCollectionCollectionIdRoute =
  ProtectedCollectionCollectionIdRouteImport.update({
    id: '/collection/$collectionId',
    path: '/collection/$collectionId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsSettingsIndexRoute =
  ProtectedSettingsSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedSettingsSettingsRoute,
  } as any)
const ProtectedPlaylistPlaylistIndexRoute =
  ProtectedPlaylistPlaylistIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedPlaylistPlaylistRoute,
  } as any)
const ProtectedSettingsSettingsTermsRoute =
  ProtectedSettingsSettingsTermsRouteImport.update({
    id: '/terms',
    path: '/terms',
    getParentRoute: () => ProtectedSettingsSettingsRoute,
  } as any)
const ProtectedSettingsSettingsProfileRoute =
  ProtectedSettingsSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => ProtectedSettingsSettingsRoute,
  } as any)
const ProtectedSettingsSettingsPrivacyRoute =
  ProtectedSettingsSettingsPrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => ProtectedSettingsSettingsRoute,
  } as any)
const ProtectedSettingsSettingsNotificationsRoute =
  ProtectedSettingsSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ProtectedSettingsSettingsRoute,
  } as any)
const ProtectedSettingsSettingsFaqRoute =
  ProtectedSettingsSettingsFaqRouteImport.update({
    id: '/faq',
    path: '/faq',
    getParentRoute: () => ProtectedSettingsSettingsRoute,
  } as any)
const ProtectedSettingsSettingsDownloadsRoute =
  ProtectedSettingsSettingsDownloadsRouteImport.update({
    id: '/downloads',
    path: '/downloads',
    getParentRoute: () => ProtectedSettingsSettingsRoute,
  } as any)
const ProtectedSettingsSettingsActivityRoute =
  ProtectedSettingsSettingsActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => ProtectedSettingsSettingsRoute,
  } as any)
const ProtectedSettingsSettingsAdminRoute =
  ProtectedSettingsSettingsAdminRouteImport.update({
    id: '/_admin',
    getParentRoute: () => ProtectedSettingsSettingsRoute,
  } as any)
const ProtectedPlaylistPlaylistCreateRoute =
  ProtectedPlaylistPlaylistCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => ProtectedPlaylistPlaylistRoute,
  } as any)
const ProtectedPlaylistPlaylistPlaylistIdRoute =
  ProtectedPlaylistPlaylistPlaylistIdRouteImport.update({
    id: '/$playlistId',
    path: '/$playlistId',
    getParentRoute: () => ProtectedPlaylistPlaylistRoute,
  } as any)
const ProtectedSettingsSettingsAdminPicksRoute =
  ProtectedSettingsSettingsAdminPicksRouteImport.update({
    id: '/picks',
    path: '/picks',
    getParentRoute: () => ProtectedSettingsSettingsAdminRoute,
  } as any)
const ProtectedSettingsSettingsAdminPermissionsRoute =
  ProtectedSettingsSettingsAdminPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => ProtectedSettingsSettingsAdminRoute,
  } as any)
const ProtectedSettingsSettingsAdminFramesRoute =
  ProtectedSettingsSettingsAdminFramesRouteImport.update({
    id: '/frames',
    path: '/frames',
    getParentRoute: () => ProtectedSettingsSettingsAdminRoute,
  } as any)
const ProtectedSettingsSettingsAdminAccessRoute =
  ProtectedSettingsSettingsAdminAccessRouteImport.update({
    id: '/access',
    path: '/access',
    getParentRoute: () => ProtectedSettingsSettingsAdminRoute,
  } as any)
const ProtectedSettingsSettingsAdminLibrariesRoute =
  ProtectedSettingsSettingsAdminLibrariesRouteImport.update({
    id: '/_libraries',
    getParentRoute: () => ProtectedSettingsSettingsAdminRoute,
  } as any)
const ProtectedSettingsSettingsAdminLibrariesUnscannedRoute =
  ProtectedSettingsSettingsAdminLibrariesUnscannedRouteImport.update({
    id: '/unscanned',
    path: '/unscanned',
    getParentRoute: () => ProtectedSettingsSettingsAdminLibrariesRoute,
  } as any)
const ProtectedSettingsSettingsAdminLibrariesLibrariesRoute =
  ProtectedSettingsSettingsAdminLibrariesLibrariesRouteImport.update({
    id: '/libraries',
    path: '/libraries',
    getParentRoute: () => ProtectedSettingsSettingsAdminLibrariesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/watch': typeof WatchRoute
  '/list': typeof ProtectedListRoute
  '/lobby': typeof ProtectedLobbyRoute
  '/movies': typeof ProtectedMoviesRoute
  '/shows': typeof ProtectedShowsRoute
  '/': typeof ProtectedIndexRoute
  '/collection/$collectionId': typeof ProtectedCollectionCollectionIdRoute
  '/company/$companyId': typeof ProtectedCompanyCompanyIdRoute
  '/movie/$mediaId': typeof ProtectedMovieMediaIdRoute
  '/person/$personId': typeof ProtectedPersonPersonIdRoute
  '/playlist': typeof ProtectedPlaylistPlaylistRouteWithChildren
  '/rooms/$roomId': typeof ProtectedRoomsRoomIdRoute
  '/settings': typeof ProtectedSettingsSettingsAdminLibrariesRouteWithChildren
  '/show/$mediaId': typeof ProtectedShowMediaIdRoute
  '/playlist/$playlistId': typeof ProtectedPlaylistPlaylistPlaylistIdRoute
  '/playlist/create': typeof ProtectedPlaylistPlaylistCreateRoute
  '/settings/activity': typeof ProtectedSettingsSettingsActivityRoute
  '/settings/downloads': typeof ProtectedSettingsSettingsDownloadsRoute
  '/settings/faq': typeof ProtectedSettingsSettingsFaqRoute
  '/settings/notifications': typeof ProtectedSettingsSettingsNotificationsRoute
  '/settings/privacy': typeof ProtectedSettingsSettingsPrivacyRoute
  '/settings/profile': typeof ProtectedSettingsSettingsProfileRoute
  '/settings/terms': typeof ProtectedSettingsSettingsTermsRoute
  '/playlist/': typeof ProtectedPlaylistPlaylistIndexRoute
  '/settings/': typeof ProtectedSettingsSettingsIndexRoute
  '/settings/access': typeof ProtectedSettingsSettingsAdminAccessRoute
  '/settings/frames': typeof ProtectedSettingsSettingsAdminFramesRoute
  '/settings/permissions': typeof ProtectedSettingsSettingsAdminPermissionsRoute
  '/settings/picks': typeof ProtectedSettingsSettingsAdminPicksRoute
  '/settings/libraries': typeof ProtectedSettingsSettingsAdminLibrariesLibrariesRoute
  '/settings/unscanned': typeof ProtectedSettingsSettingsAdminLibrariesUnscannedRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/watch': typeof WatchRoute
  '/list': typeof ProtectedListRoute
  '/lobby': typeof ProtectedLobbyRoute
  '/movies': typeof ProtectedMoviesRoute
  '/shows': typeof ProtectedShowsRoute
  '/': typeof ProtectedIndexRoute
  '/collection/$collectionId': typeof ProtectedCollectionCollectionIdRoute
  '/company/$companyId': typeof ProtectedCompanyCompanyIdRoute
  '/movie/$mediaId': typeof ProtectedMovieMediaIdRoute
  '/person/$personId': typeof ProtectedPersonPersonIdRoute
  '/playlist': typeof ProtectedPlaylistPlaylistIndexRoute
  '/rooms/$roomId': typeof ProtectedRoomsRoomIdRoute
  '/settings': typeof ProtectedSettingsSettingsAdminLibrariesRouteWithChildren
  '/show/$mediaId': typeof ProtectedShowMediaIdRoute
  '/playlist/$playlistId': typeof ProtectedPlaylistPlaylistPlaylistIdRoute
  '/playlist/create': typeof ProtectedPlaylistPlaylistCreateRoute
  '/settings/activity': typeof ProtectedSettingsSettingsActivityRoute
  '/settings/downloads': typeof ProtectedSettingsSettingsDownloadsRoute
  '/settings/faq': typeof ProtectedSettingsSettingsFaqRoute
  '/settings/notifications': typeof ProtectedSettingsSettingsNotificationsRoute
  '/settings/privacy': typeof ProtectedSettingsSettingsPrivacyRoute
  '/settings/profile': typeof ProtectedSettingsSettingsProfileRoute
  '/settings/terms': typeof ProtectedSettingsSettingsTermsRoute
  '/settings/access': typeof ProtectedSettingsSettingsAdminAccessRoute
  '/settings/frames': typeof ProtectedSettingsSettingsAdminFramesRoute
  '/settings/permissions': typeof ProtectedSettingsSettingsAdminPermissionsRoute
  '/settings/picks': typeof ProtectedSettingsSettingsAdminPicksRoute
  '/settings/libraries': typeof ProtectedSettingsSettingsAdminLibrariesLibrariesRoute
  '/settings/unscanned': typeof ProtectedSettingsSettingsAdminLibrariesUnscannedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/watch': typeof WatchRoute
  '/_protected/list': typeof ProtectedListRoute
  '/_protected/lobby': typeof ProtectedLobbyRoute
  '/_protected/movies': typeof ProtectedMoviesRoute
  '/_protected/shows': typeof ProtectedShowsRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/collection/$collectionId': typeof ProtectedCollectionCollectionIdRoute
  '/_protected/company/$companyId': typeof ProtectedCompanyCompanyIdRoute
  '/_protected/movie/$mediaId': typeof ProtectedMovieMediaIdRoute
  '/_protected/person/$personId': typeof ProtectedPersonPersonIdRoute
  '/_protected/playlist': typeof ProtectedPlaylistRouteWithChildren
  '/_protected/playlist/_playlist': typeof ProtectedPlaylistPlaylistRouteWithChildren
  '/_protected/rooms/$roomId': typeof ProtectedRoomsRoomIdRoute
  '/_protected/settings': typeof ProtectedSettingsRouteWithChildren
  '/_protected/settings/_settings': typeof ProtectedSettingsSettingsRouteWithChildren
  '/_protected/show/$mediaId': typeof ProtectedShowMediaIdRoute
  '/_protected/playlist/_playlist/$playlistId': typeof ProtectedPlaylistPlaylistPlaylistIdRoute
  '/_protected/playlist/_playlist/create': typeof ProtectedPlaylistPlaylistCreateRoute
  '/_protected/settings/_settings/_admin': typeof ProtectedSettingsSettingsAdminRouteWithChildren
  '/_protected/settings/_settings/activity': typeof ProtectedSettingsSettingsActivityRoute
  '/_protected/settings/_settings/downloads': typeof ProtectedSettingsSettingsDownloadsRoute
  '/_protected/settings/_settings/faq': typeof ProtectedSettingsSettingsFaqRoute
  '/_protected/settings/_settings/notifications': typeof ProtectedSettingsSettingsNotificationsRoute
  '/_protected/settings/_settings/privacy': typeof ProtectedSettingsSettingsPrivacyRoute
  '/_protected/settings/_settings/profile': typeof ProtectedSettingsSettingsProfileRoute
  '/_protected/settings/_settings/terms': typeof ProtectedSettingsSettingsTermsRoute
  '/_protected/playlist/_playlist/': typeof ProtectedPlaylistPlaylistIndexRoute
  '/_protected/settings/_settings/': typeof ProtectedSettingsSettingsIndexRoute
  '/_protected/settings/_settings/_admin/_libraries': typeof ProtectedSettingsSettingsAdminLibrariesRouteWithChildren
  '/_protected/settings/_settings/_admin/access': typeof ProtectedSettingsSettingsAdminAccessRoute
  '/_protected/settings/_settings/_admin/frames': typeof ProtectedSettingsSettingsAdminFramesRoute
  '/_protected/settings/_settings/_admin/permissions': typeof ProtectedSettingsSettingsAdminPermissionsRoute
  '/_protected/settings/_settings/_admin/picks': typeof ProtectedSettingsSettingsAdminPicksRoute
  '/_protected/settings/_settings/_admin/_libraries/libraries': typeof ProtectedSettingsSettingsAdminLibrariesLibrariesRoute
  '/_protected/settings/_settings/_admin/_libraries/unscanned': typeof ProtectedSettingsSettingsAdminLibrariesUnscannedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/privacy'
    | '/setup'
    | '/terms'
    | '/watch'
    | '/list'
    | '/lobby'
    | '/movies'
    | '/shows'
    | '/'
    | '/collection/$collectionId'
    | '/company/$companyId'
    | '/movie/$mediaId'
    | '/person/$personId'
    | '/playlist'
    | '/rooms/$roomId'
    | '/settings'
    | '/show/$mediaId'
    | '/playlist/$playlistId'
    | '/playlist/create'
    | '/settings/activity'
    | '/settings/downloads'
    | '/settings/faq'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/profile'
    | '/settings/terms'
    | '/playlist/'
    | '/settings/'
    | '/settings/access'
    | '/settings/frames'
    | '/settings/permissions'
    | '/settings/picks'
    | '/settings/libraries'
    | '/settings/unscanned'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/privacy'
    | '/setup'
    | '/terms'
    | '/watch'
    | '/list'
    | '/lobby'
    | '/movies'
    | '/shows'
    | '/'
    | '/collection/$collectionId'
    | '/company/$companyId'
    | '/movie/$mediaId'
    | '/person/$personId'
    | '/playlist'
    | '/rooms/$roomId'
    | '/settings'
    | '/show/$mediaId'
    | '/playlist/$playlistId'
    | '/playlist/create'
    | '/settings/activity'
    | '/settings/downloads'
    | '/settings/faq'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/profile'
    | '/settings/terms'
    | '/settings/access'
    | '/settings/frames'
    | '/settings/permissions'
    | '/settings/picks'
    | '/settings/libraries'
    | '/settings/unscanned'
  id:
    | '__root__'
    | '/_protected'
    | '/auth'
    | '/privacy'
    | '/setup'
    | '/terms'
    | '/watch'
    | '/_protected/list'
    | '/_protected/lobby'
    | '/_protected/movies'
    | '/_protected/shows'
    | '/_protected/'
    | '/_protected/collection/$collectionId'
    | '/_protected/company/$companyId'
    | '/_protected/movie/$mediaId'
    | '/_protected/person/$personId'
    | '/_protected/playlist'
    | '/_protected/playlist/_playlist'
    | '/_protected/rooms/$roomId'
    | '/_protected/settings'
    | '/_protected/settings/_settings'
    | '/_protected/show/$mediaId'
    | '/_protected/playlist/_playlist/$playlistId'
    | '/_protected/playlist/_playlist/create'
    | '/_protected/settings/_settings/_admin'
    | '/_protected/settings/_settings/activity'
    | '/_protected/settings/_settings/downloads'
    | '/_protected/settings/_settings/faq'
    | '/_protected/settings/_settings/notifications'
    | '/_protected/settings/_settings/privacy'
    | '/_protected/settings/_settings/profile'
    | '/_protected/settings/_settings/terms'
    | '/_protected/playlist/_playlist/'
    | '/_protected/settings/_settings/'
    | '/_protected/settings/_settings/_admin/_libraries'
    | '/_protected/settings/_settings/_admin/access'
    | '/_protected/settings/_settings/_admin/frames'
    | '/_protected/settings/_settings/_admin/permissions'
    | '/_protected/settings/_settings/_admin/picks'
    | '/_protected/settings/_settings/_admin/_libraries/libraries'
    | '/_protected/settings/_settings/_admin/_libraries/unscanned'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  SetupRoute: typeof SetupRoute
  TermsRoute: typeof TermsRoute
  WatchRoute: typeof WatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/playlist': {
      id: '/_protected/playlist'
      path: '/playlist'
      fullPath: '/playlist'
      preLoaderRoute: typeof ProtectedPlaylistRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/shows': {
      id: '/_protected/shows'
      path: '/shows'
      fullPath: '/shows'
      preLoaderRoute: typeof ProtectedShowsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/movies': {
      id: '/_protected/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof ProtectedMoviesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/lobby': {
      id: '/_protected/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof ProtectedLobbyRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/list': {
      id: '/_protected/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ProtectedListRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/show/$mediaId': {
      id: '/_protected/show/$mediaId'
      path: '/show/$mediaId'
      fullPath: '/show/$mediaId'
      preLoaderRoute: typeof ProtectedShowMediaIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/_settings': {
      id: '/_protected/settings/_settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsSettingsRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/rooms/$roomId': {
      id: '/_protected/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof ProtectedRoomsRoomIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/playlist/_playlist': {
      id: '/_protected/playlist/_playlist'
      path: '/playlist'
      fullPath: '/playlist'
      preLoaderRoute: typeof ProtectedPlaylistPlaylistRouteImport
      parentRoute: typeof ProtectedPlaylistRoute
    }
    '/_protected/person/$personId': {
      id: '/_protected/person/$personId'
      path: '/person/$personId'
      fullPath: '/person/$personId'
      preLoaderRoute: typeof ProtectedPersonPersonIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/movie/$mediaId': {
      id: '/_protected/movie/$mediaId'
      path: '/movie/$mediaId'
      fullPath: '/movie/$mediaId'
      preLoaderRoute: typeof ProtectedMovieMediaIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/company/$companyId': {
      id: '/_protected/company/$companyId'
      path: '/company/$companyId'
      fullPath: '/company/$companyId'
      preLoaderRoute: typeof ProtectedCompanyCompanyIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/collection/$collectionId': {
      id: '/_protected/collection/$collectionId'
      path: '/collection/$collectionId'
      fullPath: '/collection/$collectionId'
      preLoaderRoute: typeof ProtectedCollectionCollectionIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/_settings/': {
      id: '/_protected/settings/_settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedSettingsSettingsIndexRouteImport
      parentRoute: typeof ProtectedSettingsSettingsRoute
    }
    '/_protected/playlist/_playlist/': {
      id: '/_protected/playlist/_playlist/'
      path: '/'
      fullPath: '/playlist/'
      preLoaderRoute: typeof ProtectedPlaylistPlaylistIndexRouteImport
      parentRoute: typeof ProtectedPlaylistPlaylistRoute
    }
    '/_protected/settings/_settings/terms': {
      id: '/_protected/settings/_settings/terms'
      path: '/terms'
      fullPath: '/settings/terms'
      preLoaderRoute: typeof ProtectedSettingsSettingsTermsRouteImport
      parentRoute: typeof ProtectedSettingsSettingsRoute
    }
    '/_protected/settings/_settings/profile': {
      id: '/_protected/settings/_settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof ProtectedSettingsSettingsProfileRouteImport
      parentRoute: typeof ProtectedSettingsSettingsRoute
    }
    '/_protected/settings/_settings/privacy': {
      id: '/_protected/settings/_settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof ProtectedSettingsSettingsPrivacyRouteImport
      parentRoute: typeof ProtectedSettingsSettingsRoute
    }
    '/_protected/settings/_settings/notifications': {
      id: '/_protected/settings/_settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof ProtectedSettingsSettingsNotificationsRouteImport
      parentRoute: typeof ProtectedSettingsSettingsRoute
    }
    '/_protected/settings/_settings/faq': {
      id: '/_protected/settings/_settings/faq'
      path: '/faq'
      fullPath: '/settings/faq'
      preLoaderRoute: typeof ProtectedSettingsSettingsFaqRouteImport
      parentRoute: typeof ProtectedSettingsSettingsRoute
    }
    '/_protected/settings/_settings/downloads': {
      id: '/_protected/settings/_settings/downloads'
      path: '/downloads'
      fullPath: '/settings/downloads'
      preLoaderRoute: typeof ProtectedSettingsSettingsDownloadsRouteImport
      parentRoute: typeof ProtectedSettingsSettingsRoute
    }
    '/_protected/settings/_settings/activity': {
      id: '/_protected/settings/_settings/activity'
      path: '/activity'
      fullPath: '/settings/activity'
      preLoaderRoute: typeof ProtectedSettingsSettingsActivityRouteImport
      parentRoute: typeof ProtectedSettingsSettingsRoute
    }
    '/_protected/settings/_settings/_admin': {
      id: '/_protected/settings/_settings/_admin'
      path: ''
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsSettingsAdminRouteImport
      parentRoute: typeof ProtectedSettingsSettingsRoute
    }
    '/_protected/playlist/_playlist/create': {
      id: '/_protected/playlist/_playlist/create'
      path: '/create'
      fullPath: '/playlist/create'
      preLoaderRoute: typeof ProtectedPlaylistPlaylistCreateRouteImport
      parentRoute: typeof ProtectedPlaylistPlaylistRoute
    }
    '/_protected/playlist/_playlist/$playlistId': {
      id: '/_protected/playlist/_playlist/$playlistId'
      path: '/$playlistId'
      fullPath: '/playlist/$playlistId'
      preLoaderRoute: typeof ProtectedPlaylistPlaylistPlaylistIdRouteImport
      parentRoute: typeof ProtectedPlaylistPlaylistRoute
    }
    '/_protected/settings/_settings/_admin/picks': {
      id: '/_protected/settings/_settings/_admin/picks'
      path: '/picks'
      fullPath: '/settings/picks'
      preLoaderRoute: typeof ProtectedSettingsSettingsAdminPicksRouteImport
      parentRoute: typeof ProtectedSettingsSettingsAdminRoute
    }
    '/_protected/settings/_settings/_admin/permissions': {
      id: '/_protected/settings/_settings/_admin/permissions'
      path: '/permissions'
      fullPath: '/settings/permissions'
      preLoaderRoute: typeof ProtectedSettingsSettingsAdminPermissionsRouteImport
      parentRoute: typeof ProtectedSettingsSettingsAdminRoute
    }
    '/_protected/settings/_settings/_admin/frames': {
      id: '/_protected/settings/_settings/_admin/frames'
      path: '/frames'
      fullPath: '/settings/frames'
      preLoaderRoute: typeof ProtectedSettingsSettingsAdminFramesRouteImport
      parentRoute: typeof ProtectedSettingsSettingsAdminRoute
    }
    '/_protected/settings/_settings/_admin/access': {
      id: '/_protected/settings/_settings/_admin/access'
      path: '/access'
      fullPath: '/settings/access'
      preLoaderRoute: typeof ProtectedSettingsSettingsAdminAccessRouteImport
      parentRoute: typeof ProtectedSettingsSettingsAdminRoute
    }
    '/_protected/settings/_settings/_admin/_libraries': {
      id: '/_protected/settings/_settings/_admin/_libraries'
      path: ''
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsSettingsAdminLibrariesRouteImport
      parentRoute: typeof ProtectedSettingsSettingsAdminRoute
    }
    '/_protected/settings/_settings/_admin/_libraries/unscanned': {
      id: '/_protected/settings/_settings/_admin/_libraries/unscanned'
      path: '/unscanned'
      fullPath: '/settings/unscanned'
      preLoaderRoute: typeof ProtectedSettingsSettingsAdminLibrariesUnscannedRouteImport
      parentRoute: typeof ProtectedSettingsSettingsAdminLibrariesRoute
    }
    '/_protected/settings/_settings/_admin/_libraries/libraries': {
      id: '/_protected/settings/_settings/_admin/_libraries/libraries'
      path: '/libraries'
      fullPath: '/settings/libraries'
      preLoaderRoute: typeof ProtectedSettingsSettingsAdminLibrariesLibrariesRouteImport
      parentRoute: typeof ProtectedSettingsSettingsAdminLibrariesRoute
    }
  }
}

interface ProtectedPlaylistPlaylistRouteChildren {
  ProtectedPlaylistPlaylistPlaylistIdRoute: typeof ProtectedPlaylistPlaylistPlaylistIdRoute
  ProtectedPlaylistPlaylistCreateRoute: typeof ProtectedPlaylistPlaylistCreateRoute
  ProtectedPlaylistPlaylistIndexRoute: typeof ProtectedPlaylistPlaylistIndexRoute
}

const ProtectedPlaylistPlaylistRouteChildren: ProtectedPlaylistPlaylistRouteChildren =
  {
    ProtectedPlaylistPlaylistPlaylistIdRoute:
      ProtectedPlaylistPlaylistPlaylistIdRoute,
    ProtectedPlaylistPlaylistCreateRoute: ProtectedPlaylistPlaylistCreateRoute,
    ProtectedPlaylistPlaylistIndexRoute: ProtectedPlaylistPlaylistIndexRoute,
  }

const ProtectedPlaylistPlaylistRouteWithChildren =
  ProtectedPlaylistPlaylistRoute._addFileChildren(
    ProtectedPlaylistPlaylistRouteChildren,
  )

interface ProtectedPlaylistRouteChildren {
  ProtectedPlaylistPlaylistRoute: typeof ProtectedPlaylistPlaylistRouteWithChildren
}

const ProtectedPlaylistRouteChildren: ProtectedPlaylistRouteChildren = {
  ProtectedPlaylistPlaylistRoute: ProtectedPlaylistPlaylistRouteWithChildren,
}

const ProtectedPlaylistRouteWithChildren =
  ProtectedPlaylistRoute._addFileChildren(ProtectedPlaylistRouteChildren)

interface ProtectedSettingsSettingsAdminLibrariesRouteChildren {
  ProtectedSettingsSettingsAdminLibrariesLibrariesRoute: typeof ProtectedSettingsSettingsAdminLibrariesLibrariesRoute
  ProtectedSettingsSettingsAdminLibrariesUnscannedRoute: typeof ProtectedSettingsSettingsAdminLibrariesUnscannedRoute
}

const ProtectedSettingsSettingsAdminLibrariesRouteChildren: ProtectedSettingsSettingsAdminLibrariesRouteChildren =
  {
    ProtectedSettingsSettingsAdminLibrariesLibrariesRoute:
      ProtectedSettingsSettingsAdminLibrariesLibrariesRoute,
    ProtectedSettingsSettingsAdminLibrariesUnscannedRoute:
      ProtectedSettingsSettingsAdminLibrariesUnscannedRoute,
  }

const ProtectedSettingsSettingsAdminLibrariesRouteWithChildren =
  ProtectedSettingsSettingsAdminLibrariesRoute._addFileChildren(
    ProtectedSettingsSettingsAdminLibrariesRouteChildren,
  )

interface ProtectedSettingsSettingsAdminRouteChildren {
  ProtectedSettingsSettingsAdminLibrariesRoute: typeof ProtectedSettingsSettingsAdminLibrariesRouteWithChildren
  ProtectedSettingsSettingsAdminAccessRoute: typeof ProtectedSettingsSettingsAdminAccessRoute
  ProtectedSettingsSettingsAdminFramesRoute: typeof ProtectedSettingsSettingsAdminFramesRoute
  ProtectedSettingsSettingsAdminPermissionsRoute: typeof ProtectedSettingsSettingsAdminPermissionsRoute
  ProtectedSettingsSettingsAdminPicksRoute: typeof ProtectedSettingsSettingsAdminPicksRoute
}

const ProtectedSettingsSettingsAdminRouteChildren: ProtectedSettingsSettingsAdminRouteChildren =
  {
    ProtectedSettingsSettingsAdminLibrariesRoute:
      ProtectedSettingsSettingsAdminLibrariesRouteWithChildren,
    ProtectedSettingsSettingsAdminAccessRoute:
      ProtectedSettingsSettingsAdminAccessRoute,
    ProtectedSettingsSettingsAdminFramesRoute:
      ProtectedSettingsSettingsAdminFramesRoute,
    ProtectedSettingsSettingsAdminPermissionsRoute:
      ProtectedSettingsSettingsAdminPermissionsRoute,
    ProtectedSettingsSettingsAdminPicksRoute:
      ProtectedSettingsSettingsAdminPicksRoute,
  }

const ProtectedSettingsSettingsAdminRouteWithChildren =
  ProtectedSettingsSettingsAdminRoute._addFileChildren(
    ProtectedSettingsSettingsAdminRouteChildren,
  )

interface ProtectedSettingsSettingsRouteChildren {
  ProtectedSettingsSettingsAdminRoute: typeof ProtectedSettingsSettingsAdminRouteWithChildren
  ProtectedSettingsSettingsActivityRoute: typeof ProtectedSettingsSettingsActivityRoute
  ProtectedSettingsSettingsDownloadsRoute: typeof ProtectedSettingsSettingsDownloadsRoute
  ProtectedSettingsSettingsFaqRoute: typeof ProtectedSettingsSettingsFaqRoute
  ProtectedSettingsSettingsNotificationsRoute: typeof ProtectedSettingsSettingsNotificationsRoute
  ProtectedSettingsSettingsPrivacyRoute: typeof ProtectedSettingsSettingsPrivacyRoute
  ProtectedSettingsSettingsProfileRoute: typeof ProtectedSettingsSettingsProfileRoute
  ProtectedSettingsSettingsTermsRoute: typeof ProtectedSettingsSettingsTermsRoute
  ProtectedSettingsSettingsIndexRoute: typeof ProtectedSettingsSettingsIndexRoute
}

const ProtectedSettingsSettingsRouteChildren: ProtectedSettingsSettingsRouteChildren =
  {
    ProtectedSettingsSettingsAdminRoute:
      ProtectedSettingsSettingsAdminRouteWithChildren,
    ProtectedSettingsSettingsActivityRoute:
      ProtectedSettingsSettingsActivityRoute,
    ProtectedSettingsSettingsDownloadsRoute:
      ProtectedSettingsSettingsDownloadsRoute,
    ProtectedSettingsSettingsFaqRoute: ProtectedSettingsSettingsFaqRoute,
    ProtectedSettingsSettingsNotificationsRoute:
      ProtectedSettingsSettingsNotificationsRoute,
    ProtectedSettingsSettingsPrivacyRoute:
      ProtectedSettingsSettingsPrivacyRoute,
    ProtectedSettingsSettingsProfileRoute:
      ProtectedSettingsSettingsProfileRoute,
    ProtectedSettingsSettingsTermsRoute: ProtectedSettingsSettingsTermsRoute,
    ProtectedSettingsSettingsIndexRoute: ProtectedSettingsSettingsIndexRoute,
  }

const ProtectedSettingsSettingsRouteWithChildren =
  ProtectedSettingsSettingsRoute._addFileChildren(
    ProtectedSettingsSettingsRouteChildren,
  )

interface ProtectedSettingsRouteChildren {
  ProtectedSettingsSettingsRoute: typeof ProtectedSettingsSettingsRouteWithChildren
}

const ProtectedSettingsRouteChildren: ProtectedSettingsRouteChildren = {
  ProtectedSettingsSettingsRoute: ProtectedSettingsSettingsRouteWithChildren,
}

const ProtectedSettingsRouteWithChildren =
  ProtectedSettingsRoute._addFileChildren(ProtectedSettingsRouteChildren)

interface ProtectedRouteChildren {
  ProtectedListRoute: typeof ProtectedListRoute
  ProtectedLobbyRoute: typeof ProtectedLobbyRoute
  ProtectedMoviesRoute: typeof ProtectedMoviesRoute
  ProtectedShowsRoute: typeof ProtectedShowsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedCollectionCollectionIdRoute: typeof ProtectedCollectionCollectionIdRoute
  ProtectedCompanyCompanyIdRoute: typeof ProtectedCompanyCompanyIdRoute
  ProtectedMovieMediaIdRoute: typeof ProtectedMovieMediaIdRoute
  ProtectedPersonPersonIdRoute: typeof ProtectedPersonPersonIdRoute
  ProtectedPlaylistRoute: typeof ProtectedPlaylistRouteWithChildren
  ProtectedRoomsRoomIdRoute: typeof ProtectedRoomsRoomIdRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRouteWithChildren
  ProtectedShowMediaIdRoute: typeof ProtectedShowMediaIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedListRoute: ProtectedListRoute,
  ProtectedLobbyRoute: ProtectedLobbyRoute,
  ProtectedMoviesRoute: ProtectedMoviesRoute,
  ProtectedShowsRoute: ProtectedShowsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedCollectionCollectionIdRoute: ProtectedCollectionCollectionIdRoute,
  ProtectedCompanyCompanyIdRoute: ProtectedCompanyCompanyIdRoute,
  ProtectedMovieMediaIdRoute: ProtectedMovieMediaIdRoute,
  ProtectedPersonPersonIdRoute: ProtectedPersonPersonIdRoute,
  ProtectedPlaylistRoute: ProtectedPlaylistRouteWithChildren,
  ProtectedRoomsRoomIdRoute: ProtectedRoomsRoomIdRoute,
  ProtectedSettingsRoute: ProtectedSettingsRouteWithChildren,
  ProtectedShowMediaIdRoute: ProtectedShowMediaIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  SetupRoute: SetupRoute,
  TermsRoute: TermsRoute,
  WatchRoute: WatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
